### ISSUE TITLE
Stuck on loading page

### ISSUE THREAD

**Issue by pranav-ml** [Xtrendence/X-Anonymous#7]
when running locally the app gets stuck after pressing the create conversation button....even after the chat link is created the page says loading
![image_2021-10-30_212900](https://user-images.githubusercontent.com/52795266/139540424-5f4ac75f-9fd9-465d-976d-ea21647c4657.png)

**Comment by Xtrendence** [comment]
I know you closed this, but I just thought I'd mention it in case anyone else has this issue. Because of the key size, and because  all the processing is done on the client-side, the key generation and exchange process can be a bit slow. You can speed this up by opting to use a smaller key size, but it'd be a bit less secure.

**Comment by pranav-ml** [comment]
Hi, thanks for the prompt reply. Actually as I said earlier, the issue was that the page got stuck after the key was generated as you can see the url on the screenshot that I posted. I found out that the issue was that I accidentally updated the NPM modules instead of using the ones that you have provided in the repo, because of which some function was throwing an error maybe because it was deprecated or something.
